import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useMoralis } from 'react-moralis'
import GET_ACTIVE_ITEMS from '@/constants/subgraphQueries'
import { useQuery } from '@apollo/client/react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {isWeb3Enabled, chainId} = useMoralis()
  const marketplaceAddress= "0x05063b374fB4FF05ceF923a10F423f022908a571"

  const {loading , error ,data:listedNfts}= useQuery(GET_ACTIVE_ITEMS)
   

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {isWeb3Enabled?(loading||!listedNfts?(
        <div>Loading...</div>
      ):(
        listedNfts.activeItems.map((nft)=>{
          console.log(nft)
          const {price, nftAddress, tokenId, seller}= nft

          return (<div>
            <NFTBox 
            price={price}
            nftAddress= {nftAddress}
            tokenId={tokenId}
            marketplaceAddress={marketplaceAddress}
            seller={seller}
            key={`${nftAddress}${tokenId}`}
            /> 
          </div>)

        })

        
      )):""}
      <div>

      </div>



      </main>
    </>
  )
}
